version: "3.9"
services:
  start:
    image: ukaiser/docker-xc8
    command:
      - /bin/bash
      - -c
      - |
        export PATH=$$PATH:$$(pwd)
        tail -F anything
    container_name: xc8_container
    volumes:
      - .:/work_dir
volumes:
  work_dir: 
