#ifndef FIXED_MEMORY_ADDRESS_H
#define FIXED_MEMORY_ADDRESS_H

#define FIXED_ADDRESS_MEMORY

#define VENDOR_BASIC_DEMO_IN_DATA_BUFFER_ADDRESS      @0x500
#define VENDOR_BASIC_DEMO_OUT_DATA_BUFFER_ADDRESS     @0x540
#define CONTROL_BUFFER_ADDRESS_TAG                    @0x580

#endif //FIXED_MEMORY_ADDRESS